/**
 * A simple test for change a string into USB-Keyboard Scancodes:
 * http://www.win.tue.nl/~aeb/linux/kbd/scancodes-14.html
 * 
 * Official USB-Guide: Chapter 10
 * http://www.usb.org/developers/hidpage/Hut1_12v2.pdf
 * 
 * For the Keyboard-Layouts see:
 * US: http://www.goodtyping.com/teclatUS.htm
 * CH: http://home.datacomm.ch/t.bigler/sskbdsg.htm
 * Others: https://www.terena.org/activities/multiling/ml-mua/test/kbd-all.html
 * 
 * @author Lukas Zurschmiede <l.zurschmiede@ranta.ch>
 * @version 0.1
 * @package teensy_keyboard
 * @license GPL-v3
 */

// Define the Keyboard-Layout you want use
// See https://www.terena.org/activities/multiling/ml-mua/test/kbd-all.html
// See http://home.datacomm.ch/t.bigler/sskbdsg.htm
// For now: MAPPING_CH, MAPPING_DE, MAPPING_US (for all others)
//#define MAPPING_US
#define MAPPING_CH
//#define MAPPING_DE

// Uncomment the next line for debugging on a console and not using it on a teensy
//#define CONSOLE_DEBUG


/* Do not change below here. */

// Different mappings for different special chars on the different keyboard layouts
#define KEY_NONE	0x00
#define KEY_NON_US	100
#define KEY_ALTGR KEY_RIGHT_ALT

// Swiss Keyboards
#if (defined MAPPING_CH && !defined KEYBOARD_MAPPING)
#define KEYBOARD_MAPPING

#define SKEY_LEFT_CURLYBRACE KEY_QUOTE
#define SMOD_LEFT_CURLYBRACE KEY_ALTGR

#define SKEY_RIGHT_CURLYBRACE KEY_BACKSLASH
#define SMOD_RIGHT_CURLYBRACE KEY_ALTGR

#define SKEY_TILDE KEY_EQUAL
#define SMOD_TILDE KEY_ALTGR

#define SKEY_PIPE KEY_7
#define SMOD_PIPE KEY_ALTGR

#define SKEY_LEFT_SQUAREBRACE KEY_LEFT_BRACE
#define SMOD_LEFT_SQUAREBRACE KEY_ALTGR

#define SKEY_RIGHT_SQUAREBRACE KEY_RIGHT_BRACE
#define SMOD_RIGHT_SQUAREBRACE KEY_ALTGR

#define SKEY_BACKSLASH KEY_NON_US
#define SMOD_BACKSLASH KEY_ALTGR

#define SKEY_ROOF KEY_EQUAL
#define SMOD_ROOF KEY_NONE

#define SKEY_UNDERLINE KEY_SLASH
#define SMOD_UNDERLINE KEY_SHIFT

#define SKEY_BACKQUOTE KEY_QUOTE
#define SMOD_BACKQUOTE KEY_SHIFT

#define SKEY_DOUBLEPOINT KEY_PERIOD
#define SMOD_DOUBLEPOINT KEY_SHIFT

#define SKEY_SEMICOLON KEY_COMMA
#define SMOD_SEMICOLON KEY_SHIFT

#define SKEY_SMALLERTHAN KEY_NON_US
#define SMOD_SMALLERTHAN KEY_NONE

#define SKEY_GREATERTHAN KEY_NON_US
#define SMOD_GREATERTHAN KEY_SHIFT

#define SKEY_EQUAL KEY_0
#define SMOD_EQUAL KEY_SHIFT

#define SKEY_QUESTION KEY_MINUS
#define SMOD_QUESTION KEY_SHIFT

#define SKEY_AT KEY_2
#define SMOD_AT KEY_ALTGR

#define SKEY_EXCLAMATION KEY_RIGHT_BRACE
#define SMOD_EXCLAMATION KEY_SHIFT

#define SKEY_QUOTE KEY_2
#define SMOD_QUOTE KEY_SHIFT

#define SKEY_HASH KEY_3
#define SMOD_HASH KEY_ALTGR

#define SKEY_DOLLAR KEY_BACKSLASH
#define SMOD_DOLLAR KEY_NONE

#define SKEY_PERCENT KEY_5
#define SMOD_PERCENT KEY_SHIFT

#define SKEY_AND KEY_6
#define SMOD_AND KEY_SHIFT

#define SKEY_SINGLEQUOTE KEY_MINUS
#define SMOD_SINGLEQUOTE KEY_NONE

#define SKEY_LEFT_BRACE KEY_8
#define SMOD_LEFT_BRACE KEY_SHIFT

#define SKEY_RIGHT_BRACE KEY_9
#define SMOD_RIGHT_BRACE KEY_SHIFT

#define SKEY_ASTERISK KEY_3
#define SMOD_ASTERISK KEY_SHIFT

#define SKEY_PLUS KEY_1
#define SMOD_PLUS KEY_SHIFT

#define SKEY_MINUS KEY_SLASH
#define SMOD_MINUS KEY_NONE

#define SKEY_PERIOD KEY_PERIOD
#define SMOD_PERIOD KEY_NONE

#define SKEY_SLASH KEY_7
#define SMOD_SLASH KEY_SHIFT


// German keyboards
#elif (defined MAPPING_DE && !defined KEYBOARD_MAPPING)
#define KEYBOARD_MAPPING

#define SKEY_LEFT_CURLYBRACE KEY_7
#define SMOD_LEFT_CURLYBRACE KEY_ALTGR

#define SKEY_RIGHT_CURLYBRACE KEY_0
#define SMOD_RIGHT_CURLYBRACE KEY_ALTGR

#define SKEY_TILDE KEY_RIGHT_BRACE
#define SMOD_TILDE KEY_ALTGR

#define SKEY_PIPE KEY_NON_US
#define SMOD_PIPE KEY_ALTGR

#define SKEY_LEFT_SQUAREBRACE KEY_8
#define SMOD_LEFT_SQUAREBRACE KEY_ALTGR

#define SKEY_RIGHT_SQUAREBRACE KEY_9
#define SMOD_RIGHT_SQUAREBRACE KEY_ALTGR

#define SKEY_BACKSLASH KEY_MINUS
#define SMOD_BACKSLASH KEY_ALTGR

#define SKEY_ROOF KEY_TILDE
#define SMOD_ROOF KEY_NONE

#define SKEY_UNDERLINE KEY_SLASH
#define SMOD_UNDERLINE KEY_SHIFT

#define SKEY_BACKQUOTE KEY_EQUAL
#define SMOD_BACKQUOTE KEY_SHIFT

#define SKEY_DOUBLEPOINT KEY_PERIOD
#define SMOD_DOUBLEPOINT KEY_SHIFT

#define SKEY_SEMICOLON KEY_COMMA
#define SMOD_SEMICOLON KEY_SHIFT

#define SKEY_SMALLERTHAN KEY_NON_US
#define SMOD_SMALLERTHAN KEY_NONE

#define SKEY_GREATERTHAN KEY_NON_US
#define SMOD_GREATERTHAN KEY_SHIFT

#define SKEY_EQUAL KEY_0
#define SMOD_EQUAL KEY_SHIFT

#define SKEY_QUESTION KEY_MINUS
#define SMOD_QUESTION KEY_SHIFT

#define SKEY_AT KEY_Q
#define SMOD_AT KEY_ALTGR

#define SKEY_EXCLAMATION KEY_1
#define SMOD_EXCLAMATION KEY_SHIFT

#define SKEY_QUOTE KEY_2
#define SMOD_QUOTE KEY_SHIFT

#define SKEY_HASH KEY_BACKSLASH
#define SMOD_HASH KEY_NONE

#define SKEY_DOLLAR KEY_4
#define SMOD_DOLLAR KEY_SHIFT

#define SKEY_PERCENT KEY_5
#define SMOD_PERCENT KEY_SHIFT

#define SKEY_AND KEY_6
#define SMOD_AND KEY_SHIFT

#define SKEY_SINGLEQUOTE KEY_BACKSLASH
#define SMOD_SINGLEQUOTE KEY_SHIFT

#define SKEY_LEFT_BRACE KEY_8
#define SMOD_LEFT_BRACE KEY_SHIFT

#define SKEY_RIGHT_BRACE KEY_9
#define SMOD_RIGHT_BRACE KEY_SHIFT

#define SKEY_ASTERISK KEY_RIGHT_BRACE
#define SMOD_ASTERISK KEY_SHIFT

#define SKEY_PLUS KEY_RIGHT_BRACE
#define SMOD_PLUS KEY_NONE

#define SKEY_MINUS KEY_SLASH
#define SMOD_MINUS KEY_NONE

#define SKEY_PERIOD KEY_PERIOD
#define SMOD_PERIOD KEY_NONE

#define SKEY_SLASH KEY_7
#define SMOD_SLASH KEY_SHIFT


// US and others
#elif !defined KEYBOARD_MAPPING
#define KEYBOARD_MAPPING

#define SKEY_LEFT_CURLYBRACE KEY_LEFT_BRACE
#define SMOD_LEFT_CURLYBRACE KEY_SHIFT

#define SKEY_RIGHT_CURLYBRACE KEY_RIGHT_BRACE
#define SMOD_RIGHT_CURLYBRACE KEY_SHIFT

#define SKEY_TILDE KEY_TILDE
#define SMOD_TILDE KEY_SHIFT

#define SKEY_PIPE KEY_BACKSLASH
#define SMOD_PIPE KEY_SHIFT

#define SKEY_LEFT_SQUAREBRACE KEY_LEFT_BRACE
#define SMOD_LEFT_SQUAREBRACE KEY_NONE

#define SKEY_RIGHT_SQUAREBRACE KEY_RIGHT_BRACE
#define SMOD_RIGHT_SQUAREBRACE KEY_NONE

#define SKEY_BACKSLASH KEY_BACKSLASH
#define SMOD_BACKSLASH KEY_NONE

#define SKEY_ROOF KEY_6
#define SMOD_ROOF KEY_SHIFT

#define SKEY_UNDERLINE KEY_MINUS
#define SMOD_UNDERLINE KEY_SHIFT

#define SKEY_BACKQUOTE KEY_TILDE
#define SMOD_BACKQUOTE KEY_NONE

#define SKEY_DOUBLEPOINT KEY_SEMICOLON
#define SMOD_DOUBLEPOINT KEY_SHIFT

#define SKEY_SEMICOLON KEY_SEMICOLON
#define SMOD_SEMICOLON KEY_NONE

#define SKEY_SMALLERTHAN KEY_COMMA
#define SMOD_SMALLERTHAN KEY_SHIFT

#define SKEY_GREATERTHAN KEY_PERIOD
#define SMOD_GREATERTHAN KEY_SHIFT

#define SKEY_EQUAL KEY_EQUAL
#define SMOD_EQUAL KEY_NONE

#define SKEY_QUESTION KEY_SLASH
#define SMOD_QUESTION KEY_SHIFT

#define SKEY_AT KEY_2
#define SMOD_AT KEY_SHIFT

#define SKEY_EXCLAMATION KEY_1
#define SMOD_EXCLAMATION KEY_SHIFT

#define SKEY_QUOTE KEY_QUOTE
#define SMOD_QUOTE KEY_SHIFT

#define SKEY_HASH KEY_3
#define SMOD_HASH KEY_SHIFT

#define SKEY_DOLLAR KEY_4
#define SMOD_DOLLAR KEY_SHIFT

#define SKEY_PERCENT KEY_5
#define SMOD_PERCENT KEY_SHIFT

#define SKEY_AND KEY_7
#define SMOD_AND KEY_SHIFT

#define SKEY_SINGLEQUOTE KEY_QUOTE
#define SMOD_SINGLEQUOTE KEY_NONE

#define SKEY_LEFT_BRACE KEY_9
#define SMOD_LEFT_BRACE KEY_SHIFT

#define SKEY_RIGHT_BRACE KEY_0
#define SMOD_RIGHT_BRACE KEY_SHIFT

#define SKEY_ASTERISK KEY_8
#define SMOD_ASTERISK KEY_SHIFT

#define SKEY_PLUS KEY_EQUAL
#define SMOD_PLUS KEY_SHIFT

#define SKEY_MINUS KEY_MINUS
#define SMOD_MINUS KEY_NONE

#define SKEY_PERIOD KEY_PERIOD
#define SMOD_PERIOD KEY_NONE

#define SKEY_SLASH KEY_SLASH
#define SMOD_SLASH KEY_NONE

#endif
